#include QMK_KEYBOARD_H
#include "keymap_dvorak.h"
#include "sendstring_dvorak.h"

bool caps_word_press_user(uint16_t keycode) {
    switch (keycode) {
        // Keycodes that continue Caps Word, with shift applied.
        case DV_A:
        case DV_B:
        case DV_C:
        case DV_D:
        case DV_E:
        case DV_F:
        case DV_G:
        case DV_H:
        case DV_I:
        case DV_J:
        case DV_K:
        case DV_L:
        case DV_M:
        case DV_N:
        case DV_O:
        case DV_P:
        case DV_Q:
        case DV_R:
        case DV_S:
        case DV_T:
        case DV_U:
        case DV_V:
        case DV_W:
        case DV_X:
        case DV_Y:
        case DV_Z:
            add_weak_mods(MOD_BIT(KC_LSFT));  // Apply shift to next key.
            return true;

        // Keycodes that continue Caps Word, without shifting.
        case KC_1 ... KC_0:
        case KC_BSPC:
        case KC_DEL:
            return true;

        default:
            return false;  // Deactivate Caps Word.
    }
}


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(LT(2,KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, RCTL_T(KC_QUOT), KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_ESC, KC_DEL, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, RSFT_T(KC_BSLS), KC_NO, KC_LGUI, OSL(3), LT(4,KC_SPC), KC_LALT, KC_BSPC, LT(4,KC_ENT), OSL(3), KC_APP, KC_NO),
	[1] = LAYOUT(LT(2,KC_TAB), KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_SLSH, KC_LCTL, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, RCTL_T(KC_MINS), KC_LSFT, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_ESC, KC_DEL, KC_B, KC_M, KC_W, KC_V, KC_Z, RSFT_T(KC_BSLS), KC_NO, KC_LGUI, OSL(3), LT(2,KC_SPC), KC_LALT, KC_BSPC, LT(2,KC_ENT), OSL(3), KC_APP, KC_NO),
	[2] = LAYOUT(KC_NO, KC_NUM, KC_P7, KC_P8, KC_P9, KC_PMNS, KC_NO, KC_P7, KC_P8, KC_P9, KC_PMNS, KC_PSLS, KC_NO, KC_NO, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_VOLU, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_PAST, KC_NO, KC_NO, KC_P1, KC_P2, KC_P3, KC_NO, KC_NO, KC_MUTE, KC_VOLD, KC_P1, KC_P2, KC_P3, KC_PCMM, KC_PEQL, KC_P0, KC_PDOT, KC_P0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P0, KC_PDOT, KC_PCMM),
	[3] = LAYOUT(KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_SLSH, KC_LCTL, KC_LBRC, KC_RBRC, KC_MINS, KC_EQL, KC_LPRN, KC_RPRN, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_PIPE, KC_LSFT, KC_LCBR, KC_RCBR, KC_UNDS, KC_PLUS, KC_GRV, KC_TRNS, KC_TRNS, KC_NO, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(5), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[4] = LAYOUT(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_RCTL, KC_TRNS, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_PSCR, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RCTL(KC_PGDN), RCTL(KC_PGUP), KC_RCTL),
	[5] = LAYOUT(KC_NO, DF(0), DF(1), KC_NO, AG_SWAP, CG_SWAP, KC_NO, KC_NO, KC_NO, KC_PSCR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, AG_NORM, CG_NORM, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
